version: '{build}'
clone_folder: c:\projects\util_udm_appveyor_test
image:
- Visual Studio 2019
configuration:
- Release
- Debug

matrix:
  fast_finish: true


init:
- set arch=
- if "%arch%"=="Win64" ( set arch= Win64)
- echo %arch%
- echo %APPVEYOR_BUILD_WORKER_IMAGE%
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" ( set generator="Visual Studio 16 2019%arch%" )
- echo %generator%

before_build:
# download GLM https://glm.g-truc.net
- cmd: |-
    cd c:\projects\
    curl -LJO https://github.com/g-truc/glm/releases/download/0.9.9.8/glm-0.9.9.8.zip
    7z x glm-0.9.9.8.zip
    dir
- cmd: |-
    cd c:\projects\util_udm_appveyor_test
    mkdir build
- cmd: |-
    cd c:\projects\
    git clone https://github.com/Silverlan/mathutil.git
    cd mathutil
    git checkout master
    mkdir build
    cd build
    cmake .. -G %generator% -DDEPENDENCY_GLM_INCLUDE=c:\projects\glm -DSHAREDUTILS_STATIC=ON  -DDEPENDENCY_MATHUTIL_INCLUDE=C:\projects\mathutil\include\
    msbuild c:\projects\mathutil\build\mathutil.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
- cmd: |-
    cd c:\projects\util_udm_appveyor_test\build
    cmake --version
    cmake .. -G %generator%

build:
  project: build\util_udm.sln
  verbosity: normal
  parallel: true

test_script:
- cmd: |-
    cd c:\projects\util_udm_appveyor_test\build\%configuration%
    dir
    util_udm_tests.exe