version: '{build}'
clone_folder: c:\projects\util_udm_appveyor_test
image:
- Visual Studio 2019
configuration:
- Release
- Debug

matrix:
  fast_finish: true

environment:
  matrix:
  - MATHUTIL_ENABLE_MESH_FUNCTIONS: OFF
    MATHUTIL_STATIC: OFF
  - MATHUTIL_ENABLE_MESH_FUNCTIONS: ON
    MATHUTIL_STATIC: OFF

init:
- set arch=
- if "%arch%"=="Win64" ( set arch= Win64)
- echo %arch%
- echo %APPVEYOR_BUILD_WORKER_IMAGE%
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" ( set generator="Visual Studio 16 2019%arch%" )
- echo %generator%

before_build:
# download GLM https://glm.g-truc.net
- cmd: |-
    cd c:\projects\
    curl -LJO https://github.com/g-truc/glm/releases/download/0.9.9.8/glm-0.9.9.8.zip
    7z x glm-0.9.9.8.zip
    dir
# geometric tools
- ps: >-
    If ($env:MATHUTIL_ENABLE_MESH_FUNCTIONS -Match "ON") {
      cd c:\projects\
      Start-FileDownload 'https://www.geometrictools.com/Downloads/GeometricToolsEngine3p30.zip'
      7z x GeometricToolsEngine3p30.zip
      cd GeometricTools\GTEngine
      msbuild GTEngine.v16.sln
      $env:DMATHUTIL_ENABLE_MESH_FUNCTIONS="ON"
    } Else {
      $env:DMATHUTIL_ENABLE_MESH_FUNCTIONS="OFF"
    }
- cmd: |-
    cd c:\projects\util_udm_appveyor_test
    mkdir build
# clone mathutil
- cmd: |-
    cd c:\projects\
    git clone https://github.com/Silverlan/mathutil.git
    cd mathutil
    git checkout master
    mkdir build
# build sharedutils-static
- cmd: |-
    cd c:\projects\
    git clone https://github.com/Silverlan/sharedutils.git
    cd sharedutils
    git checkout master
    mkdir build-static
    cd build-static
    cmake .. -G %generator% -DDEPENDENCY_GLM_INCLUDE=c:\projects\glm -DSHAREDUTILS_STATIC=ON  -DDEPENDENCY_MATHUTIL_INCLUDE=C:\projects\mathutil\include\
    msbuild c:\projects\sharedutils\build-static\sharedutils.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
# build mathutil
- cmd: |-
    cd c:\projects\mathutil\build
    cmake .. -G %generator% -DDEPENDENCY_GLM_INCLUDE=c:\projects\glm -DDEPENDENCY_SHAREDUTILS_INCLUDE=C:\projects\sharedutils\include -DMATHUTIL_STATIC=OFF -DDEPENDENCY_SHAREDUTILS_LIBRARY_STATIC=c:\projects\sharedutils\build-static\%CONFIGURATION%\sharedutils.lib -DDEPENDENCY_GEOMETRIC_TOOLS_INCLUDE=C:\projects\GeometricTools\GTEngine\Include\ -DMATHUTIL_ENABLE_MESH_FUNCTIONS=%DMATHUTIL_ENABLE_MESH_FUNCTIONS% -DDEPENDENCY_GEOMETRIC_TOOLS_LIBRARY=C:\projects\GeometricTools\GTEngine\_Output\v142\x64\%configuration%\GTEngine.v16.lib
    msbuild c:\projects\mathutil\build\mathutil.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
# build vfilesystem
- cmd: |-
    cd c:\projects\
    git clone https://github.com/Silverlan/vfilesystem.git
    cd vfilesystem
    git checkout master
    mkdir build
    cd build
    cmake .. -G %generator% -DDEPENDENCY_GLM_INCLUDE=c:\projects\glm -DDEPENDENCY_MATHUTIL_INCLUDE=C:\projects\mathutil\include\ -DDEPENDENCY_SHAREDUTILS_INCLUDE=C:\projects\sharedutils\include -DDEPENDENCY_MATHUTIL_LIBRARY=c:\projects\mathutil\build\%CONFIGURATION%\mathutil.lib -DDEPENDENCY_SHAREDUTILS_LIBRARY=c:\projects\sharedutils\build\%CONFIGURATION%\sharedutils.lib
    msbuild c:\projects\vfilesystem\build-static\vfilesystem.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
# build util_udm_appveyor_test
- cmd: |-
    cd c:\projects\util_udm_appveyor_test\build
    cmake --version
    cmake .. -G %generator% -DDEPENDENCY_GLM_INCLUDE=c:\projects\glm -DDEPENDENCY_MATHUTIL_INCLUDE=C:\projects\mathutil\include\ -DDEPENDENCY_SHAREDUTILS_INCLUDE=C:\projects\sharedutils\include -DDEPENDENCY_VFILESYSTEM_INCLUDE=C:\projects\vfilesystem\include

build:
  project: build\util_udm.sln
  verbosity: normal
  parallel: true

test_script:
- cmd: |-
    cd c:\projects\util_udm_appveyor_test\build\%configuration%
    dir
    util_udm_tests.exe